# Generated by go2rpm 1
%bcond_without check

# https://github.com/yory8/clipman
%global goipath         github.com/yory8/clipman
Version:                1.5.2

%gometa

%global common_description %{expand:
A basic clipboard manager for Wayland, with support for persisting copy buffers
after an application exits.}

%global golicenses      COPYING
%global godocs          README.md

Name:           clipman
Release:        1%{?dist}
Summary:        A simple clipboard manager for Wayland

License:        GPLv3
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/alecthomas/template)
BuildRequires:  golang(github.com/alecthomas/units)
BuildRequires:  golang(github.com/kballard/go-shellquote)
BuildRequires:  golang(gopkg.in/alecthomas/kingpin.v2)

%description
%{common_description}

%gopkg

#%%package -n     clipman
Summary:        A simple clipboard manager for Wayland
Requires:       wl-clipboard >= 2.0

%description
%{common_description}

%prep
%goprep

%build
%gobuild -o %{gobuilddir}/bin/clipman %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
install -m 0644 -vpD docs/clipman.1  -t %{buildroot}%{_mandir}/man1/

%if %{with check}
%check
%gocheck
%endif

%files
%license COPYING
%doc README.md
%{_bindir}/*
%{_mandir}/man1/*

%gopkgfiles

%changelog
* Tue Mar 16 2021 Bob Hepple <bob.hepple@gmail.com> - 1.5.2-1
- rename spec file to %{name}.spec

* Tue Mar 02 2021 Bob Hepple <bob.hepple@gmail.com> - 1.5.2-0.2
- rebuilt RHBZ#1933950

* Thu May 14 2020 Aleksei Bavshin <alebastr89@gmail.com> - 1.5.2-0.1
- Update to 1.5.2

* Sat May 09 2020 Aleksei Bavshin <alebastr89@gmail.com> - 1.5.1-0.1
- Update to 1.5.1

* Mon May 04 2020 Aleksei Bavshin <alebastr89@gmail.com> - 1.5.0-0.1
- Update to 1.5.0

* Wed Mar 18 2020 Aleksei Bavshin <alebastr89@gmail.com> - 1.4.0-0.1
- Initial package

