# Generated by go2rpm 1
%bcond_without check

# https://github.com/cucumber/godog
%global goipath         github.com/cucumber/godog
Version:                0.11.0

%gometa

%global common_description %{expand:
Cucumber for golang.}

%global golicenses      LICENSE
%global godocs          _examples CHANGELOG.md CHANGELOG_OLD.md\\\
                        CONTRIBUTING.md README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        Cucumber for golang

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/cucumber/gherkin-go/v16)
BuildRequires:  golang(github.com/cucumber/messages-go/v13)
BuildRequires:  golang(github.com/hashicorp/go-memdb)
BuildRequires:  golang(github.com/spf13/cobra)
BuildRequires:  golang(github.com/spf13/pflag)
BuildRequires:  golang(github.com/stretchr/testify/require)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep
sed -i 's|github.com/cucumber/gherkin-go/v11|github.com/cucumber/gherkin-go/v16|' $(find . -iname "*.go" -type f)
sed -i 's|github.com/cucumber/messages-go/v10|github.com/cucumber/messages-go/v13|' $(find . -iname "*.go" -type f)


%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
# ., internal/builder: needs modules support
%gocheck -d . -t internal
%endif

%files
%license LICENSE
%doc _examples CHANGELOG.md CHANGELOG_OLD.md CONTRIBUTING.md README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.11.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Fri Jan 15 18:13:08 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 0.11.0-1
- Update to 0.11.0

* Sat Jul 25 19:56:44 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 0.10.0-1
- Initial package
