# Generated by go2rpm 1.2
%bcond_without check

# https://github.com/akamensky/argparse
%global goipath         github.com/akamensky/argparse
Version:                1.2.2

%gometa

%global common_description %{expand:
Argparse for Golang with more features as flag.}

%global golicenses      LICENSE
%global godocs          examples README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        Argparse for Golang

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.2.2-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Fri Oct 16 2020 Fabian Affolter <mail@fabian-affolter.ch> - 1.2.2-1
- Initial package