# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/christopherhein/go-version
%global goipath         go.hein.dev/go-version
%global forgeurl        https://github.com/christopherhein/go-version
Version:                0.1.0

%gometa

%global common_description %{expand:
This package gives allows you to use https://github.com/spf13/cobra and
https://github.com/goreleaser/goreleaser together to output your version in a
simple way. Supporting multiple flags for mutating the output.}

%global golicenses      LICENSE.txt
%global godocs          example CHANGELOG.md readme.adoc

Name:           %{goname}
Release:        2%{?dist}
Summary:        Golang Cobra & Goreleaser Versioning library

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/mitchellh/go-homedir)
BuildRequires:  golang(github.com/spf13/cobra)
BuildRequires:  golang(github.com/spf13/viper)
BuildRequires:  golang(sigs.k8s.io/yaml)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Wed Dec 23 11:31:23 CET 2020 Robert-André Mauchin <zebob.m@gmail.com> - 0.1.0-1
- Initial package
