# Generated by go2rpm 1
%bcond_without check

# https://github.com/tomnomnom/linkheader
%global goipath         github.com/tomnomnom/linkheader
Version:                0.1.0
%global tag             0.1.0

%gometa

%global common_description %{expand:
Golang HTTP Link header parser.}

%global golicenses      LICENSE
%global godocs          README.mkd

Name:           %{goname}
Release:        2%{?dist}
Summary:        Golang HTTP Link header parser

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Fri Jul 17 2020 Fabian Affolter <mail@fabian-affolter.ch> - 0.1.0-1
- Initial package

