# Generated by go2rpm 1
# https://github.com/google/go-jsonnet/issues/502
%ifnarch s390x %{ix86}
%bcond_without check
%endif

# https://github.com/google/go-jsonnet
%global goipath         github.com/google/go-jsonnet
Version:                0.17.0

%gometa

%global common_description %{expand:
This an implementation of Jsonnet in pure Go. It is feature complete but is not
as heavily exercised as the Jsonnet C++ implementation. Please try it out and
give feedback.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        Implementation of Jsonnet in pure Go

# Upstream license specification: Apache-2.0
License:        ASL 2.0

URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/fatih/color)
BuildRequires:  golang(github.com/sergi/go-diff/diffmatchpatch)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/jsonnet cmd/jsonnetfmt ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.17.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Fri Jan 15 21:28:16 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 0.17.0-1
- Update to 0.17.0

* Mon Jul 27 12:35:14 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 0.16.0-1
- Update to 0.16.0

* Sat Feb 01 00:48:04 CET 2020 Robert-André Mauchin <zebob.m@gmail.com> - 0.15.0-1
- Initial package
