# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/felixge/httpsnoop
%global goipath         github.com/felixge/httpsnoop
Version:                1.0.1

%gometa

%global common_description %{expand:
Package Httpsnoop provides an easy way to capture http related metrics (i.e.
response time, bytes written, and http status code) from your application's
http.Handlers.}

%global golicenses      LICENSE.txt
%global godocs          README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        Ccapture http related metrics from your application's http.Handlers

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Sat Jan 02 22:10:56 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 1.0.1-1
- Initial package
