# Generated by go2rpm 1
%bcond_without check

# https://github.com/rickb777/plural
%global goipath         github.com/rickb777/plural
Version:                1.3.0

%gometa

%global common_description %{expand:
Simple Go API for pluralisation.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        Simple Go API for pluralisation

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.3.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Thu Jan 21 22:20:40 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 1.3.0-1
- Update to 1.3.0

* Thu Oct  8 2020 Robin Lee <cheeselee@fedoraproject.org> - 1.2.2-1
- Update to 1.2.2

* Sun Sep 20 23:08:32 CST 2020 Robin Lee <cheeselee@fedoraproject.org> - 1.2.1-1
- Initial package

