# Generated by go2rpm 1.3
# Fails, dead upstream.
%bcond_with check

# https://github.com/glendc/gopher-json
%global goipath         github.com/glendc/gopher-json
Version:                0.1.0
%global tag             0.1.0

%gometa

%global common_description %{expand:
Package Json is a simple JSON encoder/decoder for gopher-lua.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        Simple JSON encoder/decoder for gopher-lua

License:        Unlicense
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/yuin/gopher-lua)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Sun Jan 10 14:04:39 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 0.1.0-1
- Initial package
