# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/twpayne/go-polyline
%global goipath         github.com/twpayne/go-polyline
Version:                1.0.1

%gometa

%global common_description %{expand:
Package Polyline implements a Google Maps Encoding Polyline encoder and
decoder.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Google Maps Encoding Polyline encoder and decoder

# Upstream license specification: BSD-2-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Jan 28 23:31:58 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 1.0.1-1
- Initial package
