# Generated by go2rpm 1
%bcond_without check

# https://github.com/jedib0t/go-pretty
%global goipath         github.com/jedib0t/go-pretty
Version:                6.0.5

%gometa

%global common_description %{expand:
Pretty print Tables and more in golang!}

%global golicenses      LICENSE
%global godocs          CODE_OF_CONDUCT.md README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        Pretty print Tables and more in golang

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/mattn/go-runewidth)
BuildRequires:  golang(github.com/pkg/profile)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 6.0.5-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Sun Jan 17 20:22:01 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 6.0.5-1
- Update to 6.0.5

* Sun Aug 23 18:21:35 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 6.0.4-4
- Fix FTBFS

* Sat Aug 01 2020 Fedora Release Engineering <releng@fedoraproject.org> - 6.0.4-3
- Second attempt - Rebuilt for
  https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Mon Jul 27 2020 Fedora Release Engineering <releng@fedoraproject.org> - 6.0.4-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Wed Jul 01 21:29:22 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 6.0.4-1
- Initial package
