# Generated by go2rpm 1.3
%bcond_without check

# https://gitea.com/lunny/log
%global goipath         gitea.com/lunny/log
%global forgeurl        https://gitea.com/lunny/log
Version:                0.2
%global repo            log
%global archivename     %{repo}-%{version}
%global archiveext      tar.gz
%global archiveurl      %{forgeurl}/archive/v%{version}.%{archiveext}
%global topdir          %{repo}
%global extractdir      %{repo}
%global scm             git

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE
%global godocs          README.md README_CN.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        None

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/mattn/go-sqlite3)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.2-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Sun Jan 10 12:46:16 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 0.2-1
- Initial package
