# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/go-gl/gl
%global goipath         github.com/go-gl/gl
%global commit          bf2b1f2f34d7f6a60a99a830f65dcd6afb0c6587

%gometa

%global godevelheader %{expand:
Requires: pkgconfig(dri)
}
%global common_description %{expand:
This package holds Go bindings to various OpenGL versions. They are
auto-generated using Glow.

Features:
 - Go functions that mirror the C specification using Go types.
 - Support for multiple OpenGL APIs (GL/GLES/EGL/WGL/GLX/EGL), versions, and profiles.
 - Support for extensions (including debug callbacks).}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Go bindings for OpenGL

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sat Jan 30 22:50:10 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 0-0.1.20210130gitbf2b1f2
- Initial package
