# Generated by rust2rpm 16
%bcond_without check
%global debug_package %{nil}

%global crate webkit2gtk

Name:           rust-%{crate}
Version:        0.11.0
Release:        1%{?dist}
Summary:        Rust bindings for webkit-gtk library

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/webkit2gtk
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Rust bindings for webkit-gtk library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+v2_10-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_10-devel %{_description}

This package contains library source intended for building other packages
which use "v2_10" feature of "%{crate}" crate.

%files       -n %{name}+v2_10-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+v2_12-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_12-devel %{_description}

This package contains library source intended for building other packages
which use "v2_12" feature of "%{crate}" crate.

%files       -n %{name}+v2_12-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+v2_14-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_14-devel %{_description}

This package contains library source intended for building other packages
which use "v2_14" feature of "%{crate}" crate.

%files       -n %{name}+v2_14-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+v2_16-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_16-devel %{_description}

This package contains library source intended for building other packages
which use "v2_16" feature of "%{crate}" crate.

%files       -n %{name}+v2_16-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+v2_18-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_18-devel %{_description}

This package contains library source intended for building other packages
which use "v2_18" feature of "%{crate}" crate.

%files       -n %{name}+v2_18-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+v2_2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_2-devel %{_description}

This package contains library source intended for building other packages
which use "v2_2" feature of "%{crate}" crate.

%files       -n %{name}+v2_2-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+v2_20-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_20-devel %{_description}

This package contains library source intended for building other packages
which use "v2_20" feature of "%{crate}" crate.

%files       -n %{name}+v2_20-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+v2_22-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_22-devel %{_description}

This package contains library source intended for building other packages
which use "v2_22" feature of "%{crate}" crate.

%files       -n %{name}+v2_22-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+v2_24-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_24-devel %{_description}

This package contains library source intended for building other packages
which use "v2_24" feature of "%{crate}" crate.

%files       -n %{name}+v2_24-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+v2_26-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_26-devel %{_description}

This package contains library source intended for building other packages
which use "v2_26" feature of "%{crate}" crate.

%files       -n %{name}+v2_26-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+v2_28-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_28-devel %{_description}

This package contains library source intended for building other packages
which use "v2_28" feature of "%{crate}" crate.

%files       -n %{name}+v2_28-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+v2_4-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_4-devel %{_description}

This package contains library source intended for building other packages
which use "v2_4" feature of "%{crate}" crate.

%files       -n %{name}+v2_4-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+v2_6-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_6-devel %{_description}

This package contains library source intended for building other packages
which use "v2_6" feature of "%{crate}" crate.

%files       -n %{name}+v2_6-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+v2_8-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_8-devel %{_description}

This package contains library source intended for building other packages
which use "v2_8" feature of "%{crate}" crate.

%files       -n %{name}+v2_8-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -a

%build
%cargo_build -a

%install
%cargo_install -a

%if %{with check}
%check
%cargo_test -a
%endif

%changelog
* Tue Mar 09 2021 Fabio Valentini <decathorpe@gmail.com> - 0.11.0-1
- Update to version 0.11.0.

* Wed Jan 27 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.10.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Wed Jul 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.10.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Fri Jul 17 2020 Josh Stone <jistone@redhat.com> - 0.10.0-1
- Update to 0.10.0

* Sat May 16 13:34:06 CEST 2020 Igor Raits <i.gnatenko.brain@gmail.com> - 0.9.2-1
- Initial package
