# Generated by rust2rpm 16
# * no tests are shipped with the published crates
# * example code adds an unnecessary dependency on libc-print (not packaged)
%bcond_with check
%global debug_package %{nil}

%global crate ctor

Name:           rust-%{crate}
Version:        0.1.20
Release:        1%{?dist}
Summary:        __attribute__((constructor)) for Rust

# Upstream license specification: Apache-2.0 OR MIT
License:        ASL 2.0 or MIT
URL:            https://crates.io/crates/ctor
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
__attribute__((constructor)) for Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-APACHE LICENSE-MIT
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Mar 28 2021 Fabio Valentini <decathorpe@gmail.com> - 0.1.20-1
- Update to version 0.1.20.
- Fixes RHBZ#1924225

* Wed Jan 27 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.18-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Tue Jan 12 2021 Fabio Valentini <decathorpe@gmail.com> - 0.1.18-1
- Update to version 0.1.18.
- Fixes RHBZ#1914978

* Thu Jan 07 2021 Fabio Valentini <decathorpe@gmail.com> - 0.1.17-1
- Initial package
