# Generated by rust2rpm 16
# tracing-log and tracing-subscriber are not packaged yet
%bcond_with check
%global debug_package %{nil}

%global crate warp

Name:           rust-%{crate}0.2
Version:        0.2.5
Release:        1%{?dist}
Summary:        Serve the web at warp speeds

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/warp
Source:         %{crates_source}
# Initial patched metadata
# * drop optional TLS feature, Rustls dependencies are not packaged
# * drop websockets feature, it's unused and depends on old crates
Patch0:         warp-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Serve the web at warp speeds.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md CHANGELOG.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+async-compression-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+async-compression-devel %{_description}

This package contains library source intended for building other packages
which use "async-compression" feature of "%{crate}" crate.

%files       -n %{name}+async-compression-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+compression-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+compression-devel %{_description}

This package contains library source intended for building other packages
which use "compression" feature of "%{crate}" crate.

%files       -n %{name}+compression-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+multipart-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+multipart-devel %{_description}

This package contains library source intended for building other packages
which use "multipart" feature of "%{crate}" crate.

%files       -n %{name}+multipart-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Mar 27 2021 Fabio Valentini <decathorpe@gmail.com> - 0.2.5-1
- Initial compat package for warp 0.2
