# Generated by rust2rpm 16
# * Tests require internet and a token
%bcond_with check
%global debug_package %{nil}

%global crate feedly_api

Name:           rust-%{crate}
Version:        0.4.6
Release:        1%{?dist}
Summary:        Rust implementation of the feedly REST API

# Upstream license specification: GPL-3.0-or-later
License:        GPLv3+
URL:            https://crates.io/crates/feedly_api
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Rust implementation of the feedly REST API.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon Mar 08 2021 Fabio Valentini <decathorpe@gmail.com> - 0.4.6-1
- Update to version 0.4.6.

* Wed Jan 27 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.4.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Sat Dec 26 12:37:53 CET 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.4.1-1
- Update to 0.4.1

* Wed Sep 16 2020 Fabio Valentini <decathorpe@gmail.com> - 0.3.8-1
- Update to version 0.3.8.

* Wed Jul 29 2020 Josh Stone <jistone@redhat.com> - 0.3.6-1
- Update to 0.3.6

* Fri Jun 26 2020 Josh Stone <jistone@redhat.com> - 0.3.5-1
- Update to 0.3.5

* Sat Jun 06 2020 Josh Stone <jistone@redhat.com> - 0.3.4-1
- Update to 0.3.4

* Thu Jun 04 16:56:43 CEST 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.3.3-1
- Update to 0.3.3

* Mon May 25 05:51:33 CEST 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.3.1-1
- Update to 0.3.1

* Fri May 22 20:03:05 CEST 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.3.0-1
- Update to 0.3.0

* Tue May 12 17:27:17 CEST 2020 Igor Raits <i.gnatenko.brain@gmail.com> - 0.2.1-1
- Initial package
