# Generated by rust2rpm 15
%bcond_without check

%global crate blsctl

Name:           rust-%{crate}
Version:        0.2.3
Release:        2%{?dist}
Summary:        Manages BLS entries and kernel cmdline options

# Upstream license specification: LGPL-2.1-or-later
License:        LGPLv2+
URL:            https://crates.io/crates/blsctl
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging
BuildRequires:  rpm-devel

%global _description %{expand:
Manages BLS entries and kernel cmdline options.}

%description %{_description}

%if ! %{__cargo_skip_build}
%package     -n %{crate}
Summary:        %{summary}
License:        GPLv3+

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE.gpl3
%{_bindir}/blsctl
%endif

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE.lgpl2
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Wed Jan 27 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.3-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Fri Nov 13 00:10:15 CET 2020 Javier Martinez Canillas <javierm@redhat.com> - 0.2.3-1
- Initial package
  Resolves: rhbz#1886464
