# Generated by rust2rpm 16
# https://github.com/rust-av/av-metrics/issues/216
%ifnarch %{ix86} %{arm}
%bcond_without check
%endif
%global debug_package %{nil}

%global crate av-metrics

Name:           rust-%{crate}
Version:        0.6.2
Release:        1%{?dist}
Summary:        Collection of algorithms for measuring audio/video metrics

# Upstream license specification: MIT
# https://github.com/rust-av/av-metrics/issues/215
License:        MIT
URL:            https://crates.io/crates/av-metrics
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Collection of algorithms for measuring audio/video metrics.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages
which use "serde" feature of "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon Mar 29 16:41:29 CEST 2021 Robert-André Mauchin <zebob.m@gmail.com> - 0.6.2-1
- Update to 0.6.2

* Wed Jan 27 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.6.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Wed Dec 09 18:17:03 CET 2020 Robert-André Mauchin <zebob.m@gmail.com> - 0.6.1-1
- Initial package
