# Generated by go2rpm 1.2
%bcond_without check

# https://github.com/redcode-labs/SNOWCRASH
%global goipath         github.com/redcode-labs/SNOWCRASH
%global commit          49b99ad798a7937d16ceaf5e183555aa498619da

%gometa

%global common_description %{expand:
A polyglot payload generator.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           snowcrash
Version:        0
Release:        0.3%{?dist}
Summary:        Polyglot payload generator

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/akamensky/argparse)
BuildRequires:  golang(github.com/chzyer/readline)
BuildRequires:  golang(github.com/common-nighthawk/go-figure)
BuildRequires:  golang(github.com/fatih/color)
BuildRequires:  golang(github.com/gobuffalo/packr)
BuildRequires:  golang(github.com/olekukonko/tablewriter)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
%gobuild -o %{gobuilddir}/bin/snowcrash %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Wed Jan 27 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Tue Nov 17 2020 Fabian Affolter <mail@fabian-affolter.ch> - 0-0.2.20200925git49b99ad
- Rename binary in the first place and don't move it (#1888976)

* Fri Oct 16 2020 Fabian Affolter <mail@fabian-affolter.ch> - 0-0.1.20200925git49b99ad
- Initial package