# Generated by go2rpm 1
%bcond_without check

# https://github.com/shurcooL/githubv4
%global goipath         github.com/shurcooL/githubv4
%global commit          234843c633fadff9694210ce7ab97948c9148a14

%gometa

%global common_description %{expand:
Package githubv4 is a client library for accessing GitHub GraphQL API v4
(https://developer.github.com/v4/).}

%global golicenses      LICENSE
%global godocs          example README.md

Name:           %{goname}
Version:        0
Release:        0.3%{?dist}
Summary:        Package githubv4 is a client library for accessing GitHub GraphQL API v4

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/shurcooL/graphql)
BuildRequires:  golang(golang.org/x/oauth2)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Wed Jan 13 16:39:45 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 0-0.2.20210113git234843c
- Bump to commit 234843c633fadff9694210ce7ab97948c9148a14

* Fri Sep 04 19:20:27 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 0-0.1.20200904gitf27d2ca
- Initial package
