# Generated by go2rpm 1
%bcond_without check

# https://github.com/adrianmo/go-nmea
%global goipath         github.com/adrianmo/go-nmea
Version:                1.3.0

%gometa

%global common_description %{expand:
A NMEA parser library in pure Go.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        NMEA parser library

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.3.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Thu Jan 14 13:00:57 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 1.3.0-1
- Update to 1.3.0

* Mon Jul 27 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.2.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Thu Jul 23 08:00:34 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 1.2.0-1
- Update to 1.2.0

* Sat Apr 04 2020 Fabian Affolter <mail@fabian-affolter.ch> - 1.1.0-1.20200404git15313ad
- Initial package
