# Generated by go2rpm 1
%bcond_without check

# https://github.com/jackc/chunkreader/v2
%global goipath         github.com/jackc/chunkreader/v2
Version:                2.0.1

%gometa

%global common_description %{expand:
Package Chunkreader provides an io.Reader wrapper that minimizes IO reads and
memory allocations.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        io.Reader wrapper that minimizes IO reads and memory allocations

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 2.0.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Sat Jul 25 13:39:20 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 2.0.1-1
- Initial package
