# Generated by go2rpm 1.3
# Needs dart and dart-sass-embedded
%bcond_with check

# https://github.com/bep/godartsass
%global goipath         github.com/bep/godartsass
Version:                0.11.0

%gometa

%global common_description %{expand:
Go API backed by the native Dart Sass Embedded executable.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        Go API backed by the native Dart Sass Embedded executable

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/cli/safeexec)
BuildRequires:  golang(google.golang.org/protobuf/proto)
BuildRequires:  golang(google.golang.org/protobuf/reflect/protoreflect)
BuildRequires:  golang(google.golang.org/protobuf/runtime/protoimpl)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/frankban/quicktest)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.11.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Sun Jan 17 22:22:37 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 0.11.0-1
- Initial package
