# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/form3tech-oss/jwt-go
%global goipath         github.com/form3tech-oss/jwt-go
Version:                3.2.2

%gometa

%global common_description %{expand:
Golang implementation of JSON Web Tokens (JWT).}

%global golicenses      LICENSE
%global godocs          MIGRATION_GUIDE.md README.md VERSION_HISTORY.md\\\
                        cmd/jwt/README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        Golang implementation of JSON Web Tokens (JWT)

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 3.2.2-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Wed Dec 23 05:59:37 CET 2020 Robert-André Mauchin <zebob.m@gmail.com> - 3.2.2-1
- Initial package
