# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/GoogleCloudPlatform/guest-logging-go
%global goipath         github.com/GoogleCloudPlatform/guest-logging-go
%global commit          6cbb518174d4efc7cb47efdd855b461732afe352

%gometa

%global common_description %{expand:
Logging facade used by GCP guest environment for structured logging}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md

Name:           %{goname}
Version:        0
Release:        1%{?dist}
Summary:        Common logger used by GCP guest environment

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(cloud.google.com/go/logging)
BuildRequires:  golang(google.golang.org/genproto/googleapis/logging/v2)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Mon Jan 25 23:54:14 UTC 2021 Eric Edens <ericedens@google.com> - 0-0.1.20210125git6cbb518
- Initial package

