# Generated by go2rpm 1
%bcond_without check

# https://github.com/hbakhtiyor/strsim
%global goipath         github.com/hbakhtiyor/strsim
%global commit          4d2bbb273edfb74e5fba86503a50daa50a9d758e

%gometa

%global common_description %{expand:
String similarity based on Dice's coefficient in go.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.2%{?dist}
Summary:        String similarity based on Dice's coefficient

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Tue Sep 22 2020 Fabian Affolter <mail@fabian-affolter.ch> - 0-0.1.20200922git4d2bbb2
- Initial package