# Generated by go2rpm 1
%bcond_without check

# https://github.com/projectdiscovery/gologger
%global goipath         github.com/projectdiscovery/gologger
Version:                1.1.3

%gometa

%global common_description %{expand:
A simple layer for leveled logging in go.}

%global godocs          README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        A simple layer for leveled logging in go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/json-iterator/go)
BuildRequires:  golang(github.com/logrusorgru/aurora)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.1.3-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Thu Jan 21 19:39:30 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 1.1.3-1
- Update to 1.1.3

* Wed Aug 26 2020 Fabian Affolter <mail@fabian-affolter.ch> - 1.0.1-1
- Update to latest upstream release 1.0.1

* Mon Jul 27 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Fri Feb 28 2020 Fabian Affolter <mail@fabian-affolter.ch> - 1.0.0-1
- Initial package for Fedora
