# Generated by go2rpm 1
%bcond_without check

# https://github.com/storj/uplink
%global goipath         storj.io/uplink
%global forgeurl        https://github.com/storj/uplink
Version:                1.4.5

%gometa

%global common_description %{expand:
Storj network Go library.}

%global golicenses      LICENSE
%global godocs          examples CODE_OF_CONDUCT.md MAINTAINERS.md README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        Storj network Go library

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/btcsuite/btcutil/base58)
BuildRequires:  golang(github.com/spacemonkeygo/monkit/v3)
BuildRequires:  golang(github.com/vivint/infectious)
BuildRequires:  golang(github.com/zeebo/errs)
BuildRequires:  golang(go.uber.org/zap)
BuildRequires:  golang(golang.org/x/sync/errgroup)
BuildRequires:  golang(storj.io/common/context2)
BuildRequires:  golang(storj.io/common/encryption)
BuildRequires:  golang(storj.io/common/errs2)
BuildRequires:  golang(storj.io/common/fpath)
BuildRequires:  golang(storj.io/common/identity)
BuildRequires:  golang(storj.io/common/macaroon)
BuildRequires:  golang(storj.io/common/memory)
BuildRequires:  golang(storj.io/common/paths)
BuildRequires:  golang(storj.io/common/pb)
BuildRequires:  golang(storj.io/common/peertls/tlsopts)
BuildRequires:  golang(storj.io/common/pkcrypto)
BuildRequires:  golang(storj.io/common/ranger)
BuildRequires:  golang(storj.io/common/readcloser)
BuildRequires:  golang(storj.io/common/rpc)
BuildRequires:  golang(storj.io/common/rpc/rpcpool)
BuildRequires:  golang(storj.io/common/rpc/rpcstatus)
BuildRequires:  golang(storj.io/common/signing)
BuildRequires:  golang(storj.io/common/socket)
BuildRequires:  golang(storj.io/common/storj)
BuildRequires:  golang(storj.io/common/sync2)
BuildRequires:  golang(storj.io/common/telemetry)
BuildRequires:  golang(storj.io/common/useragent)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(github.com/stretchr/testify/require)
BuildRequires:  golang(go.uber.org/zap/zaptest)
BuildRequires:  golang(storj.io/common/testcontext)
BuildRequires:  golang(storj.io/common/testrand)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.4.5-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Sat Jan 23 00:39:38 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 1.4.5-1
- Update to 1.4.5

* Sat Jun 20 13:30:57 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 1.3.0-1
- Initial package
