# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/martini-contrib/gzip
%global goipath         github.com/martini-contrib/gzip
%global commit          6c035326b43f79aa18793d2f1db512d21253ea61

%gometa

%global common_description %{expand:
Martini handler for adding gzip compress to requests.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.2%{?dist}
Summary:        Martini handler for adding gzip compress to requests

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/go-martini/martini)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Sat Dec 26 13:42:33 CET 2020 Robert-André Mauchin <zebob.m@gmail.com> - 0-0.1.20201226git6c03532
- Initial package
