# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/fyne-io/glfw
%global goipath         github.com/fyne-io/glfw
%global commit          f2279069162d4330df3f989e0064570b4ca4bb9d

%gometa

%global godevelheader %{expand:
Requires: pkgconfig(x11)
Requires: pkgconfig(xcursor)
Requires: pkgconfig(xrandr)
Requires: pkgconfig(xinerama)
Requires: pkgconfig(dri)
Requires: pkgconfig(xi)
Requires: pkgconfig(xxf86vm)
}

%global common_description %{expand:
Go bindings for GLFW 3.}

%global golicenses      LICENSE COPYING-glfw-3.1.txt\\\
                        COPYING-glfw-3.2.txt v3.3/glfw/glfw/LICENSE.md
%global godocs          AUTHORS README.md

%global gosupfiles      "${includes[@]}"

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Go bindings for GLFW 3

# Upstream license specification: Zlib and BSD-3-Clause
# Zlib: v3.1/glfw and v3.2/glfw
# BSD: v3.0/glfw and v3.3/glfw
License:        zlib and BSD
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep
mv v3.1/glfw/glfw/COPYING.txt COPYING-glfw-3.1.txt
mv v3.2/glfw/glfw/COPYING.txt COPYING-glfw-3.2.txt

%install
mapfile -t includes <<< $(find . -name *.c -or -name *.h -or -name *.m -type f)
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sat Jan 30 22:52:39 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 0-0.1.20210130gitf227906
- Initial package
- Close: rhbz#1922794
