# Generated by go2rpm 1
%ifarch x86_64
# Chromium is only available on these arches.
# i686 aarch64 are also available but seem to get stuck.
%bcond_without check
%else
%bcond_with check
%endif

# https://github.com/chromedp/chromedp
%global goipath         github.com/chromedp/chromedp
Version:                0.6.6

%gometa

%global common_description %{expand:
A faster, simpler way to drive browsers supporting the Chrome DevTools
Protocol.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        Drive browsers supporting the Chrome DevTools Protocol

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/chromedp/cdproto)
BuildRequires:  golang(github.com/gobwas/ws)
BuildRequires:  golang(github.com/mailru/easyjson)
%if %{with check}
BuildRequires:  chromium
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

# Chromium is broken on F34 currently.
%if %{with check} && %{fedora} <= 33
%check
%gocheck
%endif

%files

%gopkgfiles

%changelog
* Thu Feb 25 2021 Fabian Affolter <mail@fabian-affolter.ch> - 0.6.6-1
- Update to latest upstream release 0.6.6 (#1919498)

* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.6.5-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Wed Jan 13 2021 Fabian Affolter <mail@fabian-affolter.ch> - 0.6.5-1
- Update to latest upstream release 0.6.5 (#1909898)

* Sat Jan 16 2021 Elliott Sales de Andrade <quantum.analyst@gmail.com> - 0.6.4-1
- Update to latest version
- Enable tests in package

* Wed Jan 13 2021 Fabian Affolter <mail@fabian-affolter.ch> - 0.6.1-1
- Update to latest upstream release 0.6.1 (#1909898)

* Mon Jan 04 2021 Fabian Affolter <mail@fabian-affolter.ch> - 0.5.5-1
- Update to latest upstream release 0.5.5 (#1909898)

* Tue Dec 22 2020 Fabian Affolter <mail@fabian-affolter.ch> - 0.5.4-1
- Update to latest upstream release 0.5.4 (#1909898)

* Mon Jul 27 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.5.3-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Tue Apr 07 2020 Fabian Affolter <mail@fabian-affolter.ch> - 0.5.3-1
- Initial package

