# Generated by go2rpm 1
%bcond_without check

# https://github.com/moby/sys
%global goipath         github.com/moby/sys
Version:                0.2.0
%global commit          5a29239ab7e72fef7786362a4f0ff2fd4459e759

%gometa

%global common_description %{expand:
Moby sys package for Go.}

%global golicenses      LICENSE symlink/LICENSE.BSD symlink/LICENSE.APACHE
%global godocs          symlink/README.md

Name:           %{goname}
Release:        4%{?dist}
Summary:        Moby sys package for Go

# Upstream license specification: Apache-2.0 and BSD-3-Clause
# main package: ASL 2.0
# symlink package: BSD and ASL 2.0
License:        ASL 2.0 and BSD
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(golang.org/x/sys/unix)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck -d mountinfo
%endif

%gopkgfiles

%changelog
* Sun Jan 31 2021 Olivier Lemasle <o.lemasle@gmail.com> - 0.2.0-4.git5a29239
- Fix license

* Wed Jan 27 2021 Olivier Lemasle <o.lemasle@gmail.com> - 0.2.0-3.git5a29239
- Update to latest upstream commit

* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Thu Jul 30 17:45:36 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 0.2.0-1
- Initial package
