# Generated by go2rpm 1
%bcond_without check

# https://github.com/hashicorp/go-safetemp
%global goipath         github.com/hashicorp/go-safetemp
Version:                1.0.0

%gometa

%global common_description %{expand:
Functions for working safely with temporary files and directories.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        Functions for working safely with temporary files and directories

# Upstream license specification: MPL-2.0
License:        MPLv2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Mon Aug 17 00:49:35 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 1.0.0-1
- Initial package
