# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/FiloSottile/edwards25519
%global goipath         filippo.io/edwards25519
%global forgeurl        https://github.com/FiloSottile/edwards25519
Version:                1.0.0~beta.2

%gometa

%global extractdir      %(echo %{extractdir} | sed -e 's/~/-/g')
%global gosource        %(echo %{gosource} | sed -e 's/~/-/g')


%global common_description %{expand:
This library implements the edwards25519 elliptic curve, exposing the necessary
APIs to build a wide array of higher-level primitives. Read the docs at
pkg.go.dev/filippo.io/edwards25519.

The code is originally derived from Adam Langley's internal implementation in
the Go standard library, and includes George Tankersley's performance
improvements. It was then further developed by Henry de Valence for use in
ristretto255.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        Implementation of the edwards25519 elliptic curve

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.0~beta.2-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Thu Jan 21 23:52:49 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 1.0.0~beta.2-1
- Initial package
