# Generated by go2rpm 1
%bcond_without check

# https://github.com/russellhaering/goxmldsig
%global goipath         github.com/russellhaering/goxmldsig
Version:                1.1.0

%gometa

%global common_description %{expand:
Pure Go implementation of XML Digital Signatures.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        Pure Go implementation of XML Digital Signatures

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/beevik/etree)
BuildRequires:  golang(github.com/jonboulle/clockwork)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.1.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Tue Jan  5 19:29:09 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 1.1.0-1
- Update to 1.1.0
- Security fix for CVE-2020-15216
- Fix: rhbz#1884119
- Fix: rhbz#1884118

* Mon Jul 27 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Fri Feb 07 17:03:25 CET 2020 Andreas Gerstmayr <agerstmayr@redhat.com> - 0-0.1.20200207git7acd5e4
- Initial package

