# Generated by rust2rpm 17
# Disabled due to https://github.com/kennytm/mbox/issues/8
%bcond_with check
%global debug_package %{nil}

%global crate mbox

Name:           rust-%{crate}
Version:        0.5.0
Release:        4%{?dist}
Summary:        Malloc-based box

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/mbox
Source:         %{crates_source}
# Initial patched metadata
# * Bump rustc_version to 0.3, https://github.com/kennytm/mbox/pull/9
Patch0:         mbox-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Malloc-based box.
Supports wrapping pointers or null-terminated strings returned from malloc as a
Rust type, which will be free'd on drop.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE.txt
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages
which use "std" feature of "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon Mar 29 18:35:25 CEST 2021 Robert-André Mauchin <zebob.m@gmail.com> - 0.5.0-4
- Bump rustc_version to 0.3

* Wed Jan 27 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.5.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Wed Jul 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.5.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Wed Jun 17 12:19:17 CEST 2020 Igor Raits <i.gnatenko.brain@gmail.com> - 0.5.0-1
- Initial package
