# Generated by rust2rpm 16
%bcond_without check
%global debug_package %{nil}

%global crate crunchy

Name:           rust-%{crate}
Version:        0.2.2
Release:        1%{?dist}
Summary:        Crunchy unroller: deterministically unroll constant loops

# Upstream license specification: MIT
# https://github.com/Vurich/crunchy/issues/6
License:        MIT
URL:            https://crates.io/crates/crunchy
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Crunchy unroller: deterministically unroll constant loops.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+limit_1024-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+limit_1024-devel %{_description}

This package contains library source intended for building other packages
which use "limit_1024" feature of "%{crate}" crate.

%files       -n %{name}+limit_1024-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+limit_128-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+limit_128-devel %{_description}

This package contains library source intended for building other packages
which use "limit_128" feature of "%{crate}" crate.

%files       -n %{name}+limit_128-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+limit_2048-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+limit_2048-devel %{_description}

This package contains library source intended for building other packages
which use "limit_2048" feature of "%{crate}" crate.

%files       -n %{name}+limit_2048-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+limit_256-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+limit_256-devel %{_description}

This package contains library source intended for building other packages
which use "limit_256" feature of "%{crate}" crate.

%files       -n %{name}+limit_256-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+limit_512-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+limit_512-devel %{_description}

This package contains library source intended for building other packages
which use "limit_512" feature of "%{crate}" crate.

%files       -n %{name}+limit_512-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+limit_64-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+limit_64-devel %{_description}

This package contains library source intended for building other packages
which use "limit_64" feature of "%{crate}" crate.

%files       -n %{name}+limit_64-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages
which use "std" feature of "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Feb 27 19:56:14 CET 2021 Fabio Valentini <decathorpe@gmail.com> - 0.2.2-1
- Initial package
