# Generated by rust2rpm 11
%bcond_without check
%global __cargo_skip_build 0

%global crate heatseeker

Name:           rust-%{crate}
Version:        1.7.1
Release:        4%{?dist}
Summary:        Fast, robust, and portable fuzzy finder

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/heatseeker
Source:         %{crates_source}
# Initial patched metadata
# * No Windows deps
Patch0:         heatseeker-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%global _description %{expand:
Fast, robust, and portable fuzzy finder.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%doc README.md
%{_bindir}/hs

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
export TRAVIS=1
%cargo_test
%endif

%changelog
* Wed Jan 27 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.7.1-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Wed Jul 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.7.1-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.7.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Mon Dec 16 2019 Josh Stone <jistone@redhat.com> - 1.7.1-1
- Update to 1.7.1

* Mon Dec 02 08:23:40 CET 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.7.0-1
- Update to 1.7.0

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 1.6.1-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Sun Jul 21 09:08:17 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.6.1-2
- Regenerate

* Tue Apr 16 2019 Josh Stone <jistone@redhat.com> - 1.6.1-1
- Update to 1.6.1

* Sat Mar 09 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.6.0-1
- Initial package
