# Generated by rust2rpm 16
%bcond_without check
%global debug_package %{nil}

%global crate clap

Name:           rust-%{crate}
Version:        3.0.0~beta.2
Release:        2%{?dist}
Summary:        Simple to use, efficient, and full-featured Command Line Argument Parser

# Upstream license specification: MIT OR Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/clap
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Simple to use, efficient, and full-featured Command Line Argument Parser.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+atty-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+atty-devel %{_description}

This package contains library source intended for building other packages
which use "atty" feature of "%{crate}" crate.

%files       -n %{name}+atty-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+cargo-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cargo-devel %{_description}

This package contains library source intended for building other packages
which use "cargo" feature of "%{crate}" crate.

%files       -n %{name}+cargo-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+clap_derive-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+clap_derive-devel %{_description}

This package contains library source intended for building other packages
which use "clap_derive" feature of "%{crate}" crate.

%files       -n %{name}+clap_derive-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+color-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+color-devel %{_description}

This package contains library source intended for building other packages
which use "color" feature of "%{crate}" crate.

%files       -n %{name}+color-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+debug-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+debug-devel %{_description}

This package contains library source intended for building other packages
which use "debug" feature of "%{crate}" crate.

%files       -n %{name}+debug-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+derive-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+derive-devel %{_description}

This package contains library source intended for building other packages
which use "derive" feature of "%{crate}" crate.

%files       -n %{name}+derive-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+doc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+doc-devel %{_description}

This package contains library source intended for building other packages
which use "doc" feature of "%{crate}" crate.

%files       -n %{name}+doc-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+lazy_static-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+lazy_static-devel %{_description}

This package contains library source intended for building other packages
which use "lazy_static" feature of "%{crate}" crate.

%files       -n %{name}+lazy_static-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+regex-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+regex-devel %{_description}

This package contains library source intended for building other packages
which use "regex" feature of "%{crate}" crate.

%files       -n %{name}+regex-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages
which use "std" feature of "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+strsim-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+strsim-devel %{_description}

This package contains library source intended for building other packages
which use "strsim" feature of "%{crate}" crate.

%files       -n %{name}+strsim-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+suggestions-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+suggestions-devel %{_description}

This package contains library source intended for building other packages
which use "suggestions" feature of "%{crate}" crate.

%files       -n %{name}+suggestions-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+termcolor-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+termcolor-devel %{_description}

This package contains library source intended for building other packages
which use "termcolor" feature of "%{crate}" crate.

%files       -n %{name}+termcolor-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+terminal_size-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+terminal_size-devel %{_description}

This package contains library source intended for building other packages
which use "terminal_size" feature of "%{crate}" crate.

%files       -n %{name}+terminal_size-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+unstable-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unstable-devel %{_description}

This package contains library source intended for building other packages
which use "unstable" feature of "%{crate}" crate.

%files       -n %{name}+unstable-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+wrap_help-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wrap_help-devel %{_description}

This package contains library source intended for building other packages
which use "wrap_help" feature of "%{crate}" crate.

%files       -n %{name}+wrap_help-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+yaml-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+yaml-devel %{_description}

This package contains library source intended for building other packages
which use "yaml" feature of "%{crate}" crate.

%files       -n %{name}+yaml-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+yaml-rust-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+yaml-rust-devel %{_description}

This package contains library source intended for building other packages
which use "yaml-rust" feature of "%{crate}" crate.

%files       -n %{name}+yaml-rust-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%ifnarch aarch64
%cargo_test
%else
# rustdoc fails to compile some doctests on aarch64
# https://bugzilla.redhat.com/show_bug.cgi?id=1902663
%cargo_test -- --lib
%endif
%endif

%changelog
* Wed Jan 27 2021 Fedora Release Engineering <releng@fedoraproject.org> - 3.0.0~beta.2-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Fri Dec 25 11:56:29 CET 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 3.0.0~beta.2-1
- Update to 3.0.0-beta.3

* Thu Dec 10 2020 Fabio Valentini <decathorpe@gmail.com> - 2.33.3-4
- Temporarily disable doctests on aarch64.

* Wed Nov 25 2020 Fabio Valentini <decathorpe@gmail.com> - 2.33.3-3
- Remove features that have broken dependencies or are nightly-only.

* Sat Sep 26 2020 Fabio Valentini <decathorpe@gmail.com> - 2.33.3-2
- Bump strsim to 0.10.

* Thu Aug 20 2020 Josh Stone <jistone@redhat.com> - 2.33.3-1
- Update to 2.33.3

* Wed Jul 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 2.33.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Tue May 12 2020 Josh Stone <jistone@redhat.com> - 2.33.1-1
- Update to 2.33.1

* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 2.33.0-6
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 2.33.0-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Thu Jun 20 12:02:25 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.33.0-4
- Regenerate

* Sat Jun 08 23:54:09 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.33.0-3
- Regenerate

* Sun Apr 07 07:33:51 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.33.0-2
- Update strsim to 0.9

* Sat Apr 06 15:29:51 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.33.0-1
- Update to 2.33.0

* Fri Apr 05 09:42:52 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.32.0-9
- Update textwrap to 0.11

* Sun Mar 10 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.32.0-8
- Do not pull optional dependencies

* Sat Feb 02 2019 Fedora Release Engineering <releng@fedoraproject.org> - 2.32.0-7
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Fri Nov 09 2018 Josh Stone <jistone@redhat.com> - 2.32.0-6
- Expose the "doc" feature

* Sat Oct 27 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.32.0-5
- Adapt to new packaging

* Sun Oct 07 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.32.0-4
- Bump strsim to 0.8

* Sat Jul 28 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.32.0-3
- Rebuild to trigger tests

* Sat Jul 14 2018 Fedora Release Engineering <releng@fedoraproject.org> - 2.32.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_29_Mass_Rebuild

* Wed Jun 27 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.32.0-1
- Update to 2.32.0

* Thu Jun 14 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.31.2-3
- Bump regex to 1

* Wed May 02 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.31.2-2
- Bump textwrap to 0.10

* Mon Mar 26 2018 Josh Stone <jistone@redhat.com> - 2.31.2-1
- Update to 2.31.2

* Thu Feb 15 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.30.0-1
- Update to 2.30.0

* Wed Feb 07 2018 Josh Stone <jistone@redhat.com> - 2.29.4-1
- Update to 2.29.4

* Tue Feb 06 2018 Josh Stone <jistone@redhat.com> - 2.29.3-1
- Update to 2.29.3

* Fri Jan 19 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.29.2-2
- Bump strsim to 0.7

* Wed Jan 17 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.29.2-1
- Update to 2.29.2

* Wed Jan 10 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.29.1-1
- Update to 2.29.1

* Mon Jan 08 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.29.0-2
- Rebuild for rust-packaging v5

* Sat Dec 09 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.29.0-1
- Update to 2.29.0

* Thu Nov 30 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.28.0-2
- Bump lazy_static to 1

* Tue Nov 28 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.28.0-1
- Update to 2.28.0

* Thu Nov 23 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.27.1-3
- Use proper file extension for bash completions

* Mon Nov 20 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.27.1-2
- Bump version-sync to 0.5

* Thu Nov 09 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.27.1-1
- Update to 2.27.1

* Wed Jul 05 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.25.0-1
- Update to 2.25.0

* Thu Jun 15 2017 Igor Gnatenko <ignatenkobrain@fedoraproejct.org> - 2.24.2-1
- Update to 2.24.2

* Wed Jun 14 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.22.1-2
- Port to use rust-packaging

* Thu Mar 30 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.22.1-1
- Update to 2.22.1

* Wed Mar 15 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.21.1-1
- Update to 2.21.1

* Tue Feb 28 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.20.5-2
- Rebuild (vec_map)

* Sat Feb 25 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.20.5-1
- Initial package
