# Generated by rust2rpm 16
%bcond_without check
%global debug_package %{nil}

%global crate libloading

Name:           rust-%{crate}0.6
Version:        0.6.7
Release:        1%{?dist}
Summary:        Safer binding to platform’s dynamic library loading utilities

# Upstream license specification: ISC
License:        ISC
URL:            https://crates.io/crates/libloading
Source:         %{crates_source}
# Initial patched metadata
# * No windows
Patch0:         libloading-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Safer binding to platform’s dynamic library loading utilities.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.mkd
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Wed Mar 03 2021 Fabio Valentini <decathorpe@gmail.com> - 0.6.7-1
- Initial compat package for libloading 0.6
