# Generated by rust2rpm 16
%bcond_with check
%global debug_package %{nil}

%global crate textwrap

Name:           rust-%{crate}0.12
Version:        0.12.1
Release:        2%{?dist}
Summary:        Library for word wrapping, indenting, and dedenting strings

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/textwrap
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Library for word wrapping, indenting, and dedenting strings.
You can use it to format strings (such as help and error messages) for display
in commandline applications. It is designed to be efficient and handle Unicode
characters correctly.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+terminal_size-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+terminal_size-devel %{_description}

This package contains library source intended for building other packages
which use "terminal_size" feature of "%{crate}" crate.

%files       -n %{name}+terminal_size-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Wed Jan 27 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.12.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Sun Dec 27 14:52:42 CET 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.12.1-1
- Initial package
