# Generated by rust2rpm 17
%bcond_without check
%global debug_package %{nil}

%global crate signal-hook

Name:           rust-%{crate}
Version:        0.3.7
Release:        1%{?dist}
Summary:        Unix signal handling

# Upstream license specification: Apache-2.0/MIT
License:        ASL 2.0 or MIT
URL:            https://crates.io/crates/signal-hook
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Unix signal handling.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-APACHE LICENSE-MIT
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+cc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cc-devel %{_description}

This package contains library source intended for building other packages
which use "cc" feature of "%{crate}" crate.

%files       -n %{name}+cc-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+channel-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+channel-devel %{_description}

This package contains library source intended for building other packages
which use "channel" feature of "%{crate}" crate.

%files       -n %{name}+channel-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+extended-siginfo-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+extended-siginfo-devel %{_description}

This package contains library source intended for building other packages
which use "extended-siginfo" feature of "%{crate}" crate.

%files       -n %{name}+extended-siginfo-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+extended-siginfo-raw-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+extended-siginfo-raw-devel %{_description}

This package contains library source intended for building other packages
which use "extended-siginfo-raw" feature of "%{crate}" crate.

%files       -n %{name}+extended-siginfo-raw-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+iterator-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+iterator-devel %{_description}

This package contains library source intended for building other packages
which use "iterator" feature of "%{crate}" crate.

%files       -n %{name}+iterator-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Tue Mar 23 2021 Peter Robinson <pbrobinson@gmail.com> - 0.3.7-1
- Update to 0.3.7

* Wed Jan 27 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.17-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Mon Dec 28 11:35:12 CET 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.1.17-1
- Update to 0.1.17

* Wed Jul 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.16-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Fri Jun 19 2020 Josh Stone <jistone@redhat.com> - 0.1.16-1
- Update to 0.1.16

* Mon May 11 2020 Josh Stone <jistone@redhat.com> - 0.1.15-1
- Update to 0.1.15

* Tue May 05 2020 Josh Stone <jistone@redhat.com> - 0.1.14-1
- Update to 0.1.14

* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.13-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Mon Jan 27 2020 Josh Stone <jistone@redhat.com> - 0.1.13-1
- Update to 0.1.13

* Thu Nov 28 15:15:09 CET 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.12-1
- Update to 0.1.12

* Tue Nov 19 2019 Josh Stone <jistone@redhat.com> - 0.1.11-1
- Update to 0.1.11

* Sun Sep 08 09:10:52 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.10-1
- Update to 0.1.10

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.9-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Sat Jun 22 23:16:52 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.9-2
- Regenerate

* Sun Apr 28 20:37:32 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.9-1
- Update to 0.1.9

* Sun Mar 10 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.8-2
- Do not pull optional dependencies

* Tue Feb 26 2019 Josh Stone <jistone@redhat.com> - 0.1.8-1
- Update to 0.1.8

* Sat Feb 09 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.7-3
- Run tests in infrastructure

* Sat Feb 02 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.7-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Tue Jan 08 2019 Josh Stone <jistone@redhat.com> - 0.1.7-1
- Update to 0.1.7

* Thu Nov 15 2018 Josh Stone <jistone@redhat.com> - 0.1.6-1
- Initial package
