# Generated by rust2rpm 17
# * temporarily disable test suite to work around LLVM 11 codegen issues
#   since Rust 1.50.0:
#   https://bugzilla.redhat.com/show_bug.cgi?id=1920403#c1
%bcond_with check
%global debug_package %{nil}

%global crate rand

Name:           rust-%{crate}
Version:        0.8.3
Release:        1%{?dist}
Summary:        Random number generators and other randomness functionality

# Upstream license specification: MIT OR Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/rand
Source:         %{crates_source}
# Initial patched metadata
# * Remove non-unix dependencies
Patch0:         rand-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Random number generators and other randomness functionality.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-MIT LICENSE-APACHE COPYRIGHT
%doc README.md CHANGELOG.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+alloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alloc-devel %{_description}

This package contains library source intended for building other packages
which use "alloc" feature of "%{crate}" crate.

%files       -n %{name}+alloc-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+getrandom-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+getrandom-devel %{_description}

This package contains library source intended for building other packages
which use "getrandom" feature of "%{crate}" crate.

%files       -n %{name}+getrandom-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+libc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libc-devel %{_description}

This package contains library source intended for building other packages
which use "libc" feature of "%{crate}" crate.

%files       -n %{name}+libc-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+log-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+log-devel %{_description}

This package contains library source intended for building other packages
which use "log" feature of "%{crate}" crate.

%files       -n %{name}+log-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+rand_chacha-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rand_chacha-devel %{_description}

This package contains library source intended for building other packages
which use "rand_chacha" feature of "%{crate}" crate.

%files       -n %{name}+rand_chacha-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages
which use "serde" feature of "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+serde1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde1-devel %{_description}

This package contains library source intended for building other packages
which use "serde1" feature of "%{crate}" crate.

%files       -n %{name}+serde1-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+small_rng-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+small_rng-devel %{_description}

This package contains library source intended for building other packages
which use "small_rng" feature of "%{crate}" crate.

%files       -n %{name}+small_rng-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages
which use "std" feature of "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+std_rng-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std_rng-devel %{_description}

This package contains library source intended for building other packages
which use "std_rng" feature of "%{crate}" crate.

%files       -n %{name}+std_rng-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Mar 28 2021 Fabio Valentini <decathorpe@gmail.com> - 0.8.3-1
- Update to version 0.8.3.
- Fixes RHBZ#1920403

* Wed Jan 27 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.8.2-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Wed Jan 13 2021 Fabio Valentini <decathorpe@gmail.com> - 0.8.2-1
- Update to version 0.8.2.
- Fixes RHBZ#1915720

* Mon Jan 11 18:18:42 CET 2021 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.8.1-1
- Update to 0.8.1 (Fixes: RHBZ#1912524)

* Sun Jan 03 10:43:35 CET 2021 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.8.0-1
- Update to 0.8.0 (Fixes: RHBZ#1909311)

* Fri Dec 11 2020 Fabio Valentini <decathorpe@gmail.com> - 0.7.3-4
- Remove features with missing dependencies (packed_simd, stdweb, wasm-bindgen).

* Wed Jul 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.7.3-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.7.3-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Wed Jan 15 2020 Josh Stone <jistone@redhat.com> - 0.7.3-1
- Update to 0.7.3

* Fri Dec 20 19:28:37 CET 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.7.2-2
- Regenerate

* Tue Sep 17 07:51:27 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.7.2-1
- Update to 0.7.2

* Sun Sep 15 19:19:25 CEST 2019 Robert-André Mauchin <zebob.m@gmail.com> - 0.7.1-1
- Update to 0.7.1

* Sun Aug 04 12:00:58 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.7.0-1
- Update to 0.7.0

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.6.5-6
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Thu Jun 20 11:42:26 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.6.5-5
- Regenerate

* Sun Jun 09 14:58:38 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.6.5-4
- Regenerate

* Sun Mar 10 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.6.5-3
- Do not pull optional dependencies

* Sat Feb 02 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.6.5-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Mon Jan 28 2019 Josh Stone <jistone@redhat.com> - 0.6.5-1
- Update to 0.6.5

* Thu Jan 10 2019 Josh Stone <jistone@redhat.com> - 0.6.4-1
- Update to 0.6.4

* Mon Dec 03 2018 Igor Gnatenko <ignatenkobrian@fedoraproject.org> - 0.6.1-1
- Update to 0.6.1

* Sat Oct 27 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.5.5-3
- Adapt to new packaging

* Sun Oct 07 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.5.5-2
- Run tests in infrastructure

* Wed Aug 08 2018 Josh Stone <jistone@redhat.com> - 0.5.5-1
- Update to 0.5.5

* Fri Jul 13 2018 Josh Stone <jistone@redhat.com> - 0.5.4-1
- Update to 0.5.4

* Thu Jul 05 2018 Josh Stone <jistone@redhat.com> - 0.5.3-2
- Fix the python2 exclusion

* Sat Jun 30 2018 Josh Stone <jistone@redhat.com> - 0.5.3-1
- Update to 0.5.3

* Tue Feb 20 2018 Josh Stone <jistone@redhat.com> - 0.4.2-4
- Exclude python2 utilities

* Fri Feb 09 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0.4.2-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_28_Mass_Rebuild

* Mon Jan 08 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.4.2-2
- Rebuild for rust-packaging v5

* Sat Jan 06 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.4.2-1
- Update to 0.4.2

* Sun Dec 31 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.4.1-1
- Update to 0.4.1

* Tue Nov 07 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.18-1
- Update to 0.3.18

* Fri Oct 27 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.17-1
- Update to 0.3.17

* Wed Jun 14 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.15-3
- Port to use rust-packaging

* Fri Feb 24 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.15-2
- Use rich dependencies

* Sun Feb 12 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.15-1
- Initial package
