# Generated by go2rpm 1
# fork has diverged from upstream while relying on said upstream for comparison
# in test: https://github.com/pingcap/errors/issues/14
%bcond_with check

# https://github.com/pingcap/errors
%global goipath         github.com/pingcap/errors
Version:                0.11.4

%gometa

%global common_description %{expand:
Simple error handling primitives.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        Simple error handling primitives

# Upstream license specification: BSD-2-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/pkg/errors)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.11.4-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Wed Aug 12 18:27:04 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 0.11.4-1
- Initial package
