# Generated by go2rpm
%bcond_without check

# https://github.com/opencontainers/selinux
%global goipath         github.com/opencontainers/selinux
Version:                1.8.0

%gometa

%global common_description %{expand:
Common SELinux package used across the container ecosystem.}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md README.md

%global gosupfiles      ${selinux[@]}

Name:           %{goname}
Release:        2%{?dist}
Summary:        Common SELinux implementation

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/pkg/errors)
BuildRequires:  golang(github.com/willf/bitset)
BuildRequires:  golang(golang.org/x/sys/unix)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
mapfile -t selinux <<< $(find . -name "*.go" -type f)
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.8.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Mon Dec 21 09:28:52 CET 2020 Robert-André Mauchin <zebob.m@gmail.com> - 1.8.0-1
- Update to 1.8.0
- Close: rhbz#1905732

* Thu Jul 30 18:01:26 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 1.6.0-1
- Update to 1.6.0

* Mon Jul 27 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.2.2-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Wed Jan 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.2.2-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Thu Jul 25 2019 Fedora Release Engineering <releng@fedoraproject.org> - 1.2.2-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Sat May 04 17:43:15 CEST 2019 Robert-André Mauchin <zebob.m@gmail.com> - 1.2.2-1
- Initial package
