# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/Masterminds/goutils
%global goipath         github.com/Masterminds/goutils
Version:                1.1.0

%gometa

%global common_description %{expand:
GoUtils is a Go implementation of some string manipulation libraries of Apache
Commons. This is an open source project aimed at providing Go users with
utility functions to manipulate strings in various ways.}

%global golicenses      LICENSE.txt
%global godocs          CHANGELOG.md README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        String manipulation libraries of Apache Commons

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}
# Go 1.15: https://github.com/Masterminds/goutils/pull/32
Patch0:         0001-Explicitly-convert-digits-to-runes-before-strings.patch

%description
%{common_description}

%gopkg

%prep
%goprep
%patch0 -p1

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.1.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Sun Jan 03 15:36:25 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 1.1.0-1
- Initial package
