# Generated by go2rpm 1
%bcond_without check

# https://github.com/fnproject/fdk-go
%global goipath         github.com/fnproject/fdk-go
Version:                0.0.3

%gometa

%global common_description %{expand:
Go language helper funcs for fn.}

%global golicenses      LICENSE
%global godocs          examples CONTRIBUTING.md README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        Go language helper funcs for fn

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.0.3-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Fri Jan 15 20:09:42 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 0.0.3-1
- Update to 0.0.3

* Thu Jul 30 19:47:05 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 0.0.2-1
- Initial package
