# Generated by go2rpm
%bcond_without check

# https://github.com/google/uuid
%global goipath         github.com/google/uuid
Version:                1.1.4

%gometa

%global common_description %{expand:
The Uuid package generates and inspects UUIDs based on RFC 4122 and DCE 1.1:
Authentication and Security Services.

This package is based on the github.com/pborman/uuid package (previously named
code.google.com/p/go-uuid). It differs from these earlier packages in that a
UUID is a 16 byte array rather than a byte slice. One loss due to this change is
the ability to represent an invalid UUID (vs a NIL UUID).}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md CONTRIBUTORS README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        Go library to generate and inspect UUIDs

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.1.4-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Tue Jan  5 17:14:32 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 1.1.4-1
- Update to 1.1.4
- Close: rhbz#1912600

* Sat Jan  2 22:04:10 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 1.1.3-1
- Update to 1.1.3
- Close: rhbz#1873697

* Fri Dec 11 2020 Ondřej Budai <ondrej@budai.cz> - 1.1.2-1
- Rebase to 1.1.2

* Mon Jul 27 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.1.1-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Wed Jan 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.1.1-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Thu Jul 25 2019 Fedora Release Engineering <releng@fedoraproject.org> - 1.1.1-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Fri Apr 26 20:47:12 CEST 2019 Robert-André Mauchin <zebob.m@gmail.com> - 1.1.1-2
- Update to new macros

* Thu Feb 28 2019 Carl George <carl@george.computer> - 1.1.1-1
- Latest upstream

* Mon Feb 11 2019 Carl George <carl@george.computer> - 1.1.0-1
- Initial package
