# Generated by go2rpm 1
%bcond_without check

# https://github.com/mvdan/gofumpt
%global goipath         mvdan.cc/gofumpt
%global forgeurl        https://github.com/mvdan/gofumpt
Version:                0.1.0

%gometa

%global common_description %{expand:
A stricter gofmt.}

%global golicenses      LICENSE LICENSE.google
%global godocs          README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        A stricter gofmt

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/google/go-cmp/cmp)
BuildRequires:  golang(golang.org/x/mod/module)
BuildRequires:  golang(golang.org/x/mod/semver)
BuildRequires:  golang(golang.org/x/tools/go/ast/astutil)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/rogpeppe/go-internal/gotooltest)
BuildRequires:  golang(github.com/rogpeppe/go-internal/testscript)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Wed Jan 13 22:10:18 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 0.1.0-1
- Update to 0.1.0

* Fri Sep 18 03:29:15 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 0-0.1.20200918gitab5a819
- Initial package
