# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/insomniacslk/xjson
%global goipath         github.com/insomniacslk/xjson
%global commit          bc4ec6a4393c051f9a95ea2c176548296206e79b

%gometa

%global common_description %{expand:
Extended JSON marshallers and unmarshallers (like URL, Time, etc).}

%global golicenses      COPYING
Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Extended JSON marshallers and unmarshallers (like URL, Time, etc)

# Upstream license specification: BSD-2-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Mon Jan  4 2021 Davide Cavalca <dcavalca@fedoraproject.org> - 0-0.1.20210104gitbc4ec6a
- Initial package

