# Generated by go2rpm 1
# Needs network access
%bcond_with check

# https://github.com/schollz/progressbar/v3
%global goipath         github.com/schollz/progressbar/v3
%global forgeurl        https://github.com/schollz/progressbar
Version:                3.7.3

%gometa

%global common_description %{expand:
A very simple thread-safe progress bar which should work on every OS without
problems. I needed a progressbar for croc and everything I tried had problems,
so I made another one.}

%global golicenses      LICENSE
%global godocs          examples README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        A really basic thread-safe progress bar for Golang applications

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/k0kubun/go-ansi)
BuildRequires:  golang(github.com/mattn/go-runewidth)
BuildRequires:  golang(github.com/mitchellh/colorstring)
BuildRequires:  golang(golang.org/x/crypto/ssh/terminal)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 3.7.3-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Thu Jan 21 22:30:06 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 3.7.3-1
- Update to 3.7.3

* Thu Sep 17 21:10:06 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 3.5.1-1
- Initial package
