# Generated by go2rpm 1
%bcond_without check

# https://github.com/iancoleman/strcase
%global goipath         github.com/iancoleman/strcase
Version:                0.1.3

%gometa

%global common_description %{expand:
A Golang package for converting to snake_case or CamelCase.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        A Golang package for converting to snake_case or CamelCase

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.3-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Sun Jan 17 17:33:36 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 0.1.3-1
- Update to 0.1.3

* Thu Sep 03 20:40:41 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 0.1.1-1
- Initial package
