# Generated by go2rpm 1
%bcond_without check

# https://github.com/go-chi/render
%global goipath         github.com/go-chi/render
Version:                1.0.1

%gometa

%global common_description %{expand:
Easily manage HTTP request / response payloads of Go HTTP services.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        Easily manage HTTP request / response payloads of Go HTTP services

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Mon Jul 27 23:46:31 CST 2020 Qiyu Yan <yanqiyu@fedoraproject.org> - 1.0.1-1
- Initial package

