# Generated by go2rpm 1.3
# Rounding errors
%ifarch x86_64
%bcond_without check
%endif

# https://github.com/twpayne/go-geom
%global goipath         github.com/twpayne/go-geom
Version:                1.3.6

%gometa

%global common_description %{expand:
Package Geom implements efficient geometry types for geospatial applications.}

%global golicenses      LICENSE
%global godocs          examples INTERNALS.md README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Efficient geometry types for geospatial applications

# Upstream license specification: BSD-2-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/lib/pq)
BuildRequires:  golang(github.com/twpayne/go-kml)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/DATA-DOG/go-sqlmock)
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Jan 28 23:28:58 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 1.3.6-1
- Initial package
