# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/Kodeworks/golang-image-ico
%global goipath         github.com/Kodeworks/golang-image-ico
%global commit          73f0f4cfade9008b7c0938a8224ececaa7733883

%gometa

%global common_description %{expand:
Golang support for Windows .ico file format.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Golang support for Windows .ico file format

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sat Jan 30 21:47:48 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 0-0.1.20210130git73f0f4c
- Initial package
