# Generated by go2rpm 1
%bcond_without check

# https://github.com/coocood/freecache
%global goipath         github.com/coocood/freecache
Version:                1.1.1

%gometa

%global common_description %{expand:
A cache library for Go with zero GC overhead.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        3%{?dist}
Summary:        Cache library with zero GC overhead

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/cespare/xxhash)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.1.1-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Thu Nov 19 2020 Fabian Affolter <mail@fabian-affolter.ch> -1.1.1-2
- Remove demo server (#1881612)

* Tue Sep 22 2020 Fabian Affolter <mail@fabian-affolter.ch> - 1.1.1-1
- Initial package