# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/hetznercloud/hcloud-go
%global goipath         github.com/hetznercloud/hcloud-go
Version:                1.23.1

%gometa

%global common_description %{expand:
A Go library for the Hetzner Cloud API.}

%global golicenses      LICENSE
%global godocs          CHANGES.md README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        Go library for the Hetzner Cloud API

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/google/go-cmp/cmp)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.23.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Thu Dec 03 13:35:28 CET 2020 Robert-André Mauchin <zebob.m@gmail.com> - 1.23.1-1
- Initial package

