# Generated by go2rpm
%bcond_without check

# https://github.com/alecthomas/kong
%global goipath         github.com/alecthomas/kong
Version:                0.2.16

%gometa

%global common_description %{expand:
Kong is a command-line parser for Go.}

%global golicenses      COPYING
%global godocs          _examples README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Command-line parser for Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/pkg/errors)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sat Mar 13 2021 Elliott Sales de Andrade <quantum.analyst@gmail.com> - 0.2.16-1
- Update to latest version (#1937064)

* Tue Feb 09 2021 Elliott Sales de Andrade <quantum.analyst@gmail.com> - 0.2.15-1
- Update to latest version (#1926720)

* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.12-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Fri Dec 04 2020 Elliott Sales de Andrade <quantum.analyst@gmail.com> - 0.2.12-1
- Update to latest version (#1904359)

* Mon Jul 27 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.11-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Sun Jul 12 2020 Elliott Sales de Andrade <quantum.analyst@gmail.com> - 0.2.11-1
- Update to latest version

* Thu Apr 30 2020 Elliott Sales de Andrade <quantum.analyst@gmail.com> - 0.2.9-1
- Update to latest version

* Sun Apr 26 2020 Elliott Sales de Andrade <quantum.analyst@gmail.com> - 0.2.7-1
- Update to latest version

* Fri Apr 17 2020 Elliott Sales de Andrade <quantum.analyst@gmail.com> - 0.2.5-1
- Update to latest version

* Sat Mar 07 2020 Elliott Sales de Andrade <quantum.analyst@gmail.com> - 0.2.4-1
- Update to latest version

* Tue Mar 03 2020 Elliott Sales de Andrade <quantum.analyst@gmail.com> - 0.2.3-1
- Update to latest version

* Sat Feb 15 2020 Elliott Sales de Andrade <quantum.analyst@gmail.com> - 0.2.2-1
- Update to latest version

* Tue Jan 28 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Wed Oct 30 2019 Elliott Sales de Andrade <quantum.analyst@gmail.com> - 0.2.1-1
- Update to latest version

* Thu Jul 25 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Wed Jul 10 04:35:16 EDT 2019 Elliott Sales de Andrade <quantum.analyst@gmail.com> - 0.2.0-1
- Update to latest version

* Tue Jun 04 15:06:52 CEST 2019 Robert-André Mauchin <zebob.m@gmail.com> - 0.1.16-2
- Update to new macros

* Mon Apr 01 2019 Elliott Sales de Andrade <quantum.analyst@gmail.com> - 0.1.16-1
- Update to latest version

* Thu Feb 28 2019 Elliott Sales de Andrade <quantum.analyst@gmail.com> - 0.1.15-1
- First package for Fedora
