# Generated by go2rpm 1.2
%bcond_without check

# https://github.com/teambition/rrule-go
%global goipath         github.com/teambition/rrule-go
Version:                1.6.2

%gometa

%global common_description %{expand:
Go library for working with recurrence rules for calendar dates.}

%global golicenses      LICENSE
%global godocs          example README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        Go library for working with recurrence rules for calendar dates

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.6.2-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Sat Nov  7 2020 Robin Lee <cheeselee@fedoraproject.org> - 1.6.2-1
- Update to 1.6.2

* Sun Oct 18 19:46:24 CST 2020 Robin Lee <cheeselee@fedoraproject.org> - 1.6.1-1
- Initial package

