# Generated by go2rpm 1
# Needs privileges
%bcond_with check

# https://github.com/cilium/ebpf
%global goipath         github.com/cilium/ebpf
Version:                0.3.0

%gometa

%global common_description %{expand:
eBPF is a pure Go library that provides utilities for loading, compiling, and
debugging eBPF programs. It has minimal external dependencies and is intended to
be used in long running processes.}

%global golicenses      LICENSE
%global godocs          CODE_OF_CONDUCT.md readme.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        eBPF Library for Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(golang.org/x/sys/unix)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/google/go-cmp/cmp)
BuildRequires:  golang(github.com/google/go-cmp/cmp/cmpopts)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.3.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Fri Jan  8 23:21:32 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 0.3.0-1
- Update to 0.3.0

* Mon Jul 27 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Fri Jul 24 23:27:31 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 0-0.2.20200724git1c8d4c9
- Bump to commit 1c8d4c9ef7759622653a1d319284a44652333b28

* Thu Mar 05 15:15:28 CET 2020 Robert-André Mauchin <zebob.m@gmail.com> - 0-0.1.20200305git5d50e74
- Initial package
