# Generated by go2rpm 1.2
%bcond_without check

# https://github.com/hakluke/hakrevdns
%global goipath         github.com/hakluke/hakrevdns
%global commit          9fa2d590700167e3738ec33bdb4345967dc6c01a

%gometa

%global common_description %{expand:
Small, fast tool for performing reverse DNS lookups en masse.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           hakrevdns
Version:        0
Release:        0.2%{?dist}
Summary:        Tool for performing reverse DNS lookups

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/jessevdk/go-flags)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
%gobuild -o %{gobuilddir}/bin/hakrevdns %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Fri Oct 16 2020 Fabian Affolter <mail@fabian-affolter.ch> - 0-0.1.20201016git9fa2d59
- Initial package