# Generated by rust2rpm 17
%bcond_without check
%global debug_package %{nil}

%global crate v_escape

Name:           rust-%{crate}
Version:        0.15.0
Release:        2%{?dist}
Summary:        Simd optimized escaping code

# Upstream license specification: MIT/Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/v_escape
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Simd optimized escaping code.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+buf-min-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+buf-min-devel %{_description}

This package contains library source intended for building other packages
which use "buf-min" feature of "%{crate}" crate.

%files       -n %{name}+buf-min-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+bytes-buf-tokio2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bytes-buf-tokio2-devel %{_description}

This package contains library source intended for building other packages
which use "bytes-buf-tokio2" feature of "%{crate}" crate.

%files       -n %{name}+bytes-buf-tokio2-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+bytes-buf-tokio3-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bytes-buf-tokio3-devel %{_description}

This package contains library source intended for building other packages
which use "bytes-buf-tokio3" feature of "%{crate}" crate.

%files       -n %{name}+bytes-buf-tokio3-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Wed Jan 27 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.15.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Sun Jan 03 10:51:01 CET 2021 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.15.0-1
- Update to 0.15.0 (Fixes: RHBZ#1909862)

* Mon Nov 30 2020 Fabio Valentini <decathorpe@gmail.com> - 0.14.1-1
- Update to version 0.14.1.
- Fixes RHBZ#1902619

* Wed Nov 25 2020 Fabio Valentini <decathorpe@gmail.com> - 0.14.0-1
- Update to version 0.14.0.

* Thu Oct 01 2020 Fabio Valentini <decathorpe@gmail.com> - 0.13.1-1
- Update to version 0.13.1.

* Mon Sep 21 2020 Fabio Valentini <decathorpe@gmail.com> - 0.12.1-1
- Update to version 0.12.1.

* Wed Jul 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.7.4-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.7.4-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Wed Dec 11 20:50:10 CET 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.7.4-1
- Update to 0.7.4

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.7.2-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Sat Jun 22 23:13:56 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.7.2-2
- Regenerate

* Thu May 30 18:17:10 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.7.2-1
- Initial package
