# Generated by rust2rpm 16
%bcond_without check
%global __cargo_skip_build 0

%global crate bodhi-cli

Name:           rust-%{crate}
Version:        1.0.1
Release:        1%{?dist}
Summary:        Bodhi CLI client based on bodhi-rs

# Upstream license specification: MIT OR Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/bodhi-cli
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%global _description %{expand:
Bodhi CLI client based on bodhi-rs.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# ASL 2.0
# ASL 2.0 or Boost
# ASL 2.0 or MIT
# BSD
# MIT
# MIT or ASL 2.0
# Unlicense or MIT
# zlib
# zlib or ASL 2.0 or MIT
License:        ASL 2.0 and BSD and MIT and zlib

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE-APACHE LICENSE-MIT
%doc README.md NEWS.md
%{_bindir}/bodhi-cli

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon Mar 08 2021 Fabio Valentini <decathorpe@gmail.com> - 1.0.1-1
- Update to version 1.0.1.

* Wed Jan 27 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Tue Dec 15 2020 Fabio Valentini <decathorpe@gmail.com> - 1.0.0-1
- Update to version 1.0.0.

* Tue Nov 03 2020 Fabio Valentini <decathorpe@gmail.com> - 0.4.1-1
- Update to version 0.4.1.

* Sun Aug 30 2020 Fabio Valentini <decathorpe@gmail.com> - 0.3.3-5
- Rebuild for bodhi 0.6.2.

* Sun Aug 16 15:01:11 GMT 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.3.3-4
- Rebuild

* Sat Aug 01 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.3.3-3
- Second attempt - Rebuilt for
  https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Wed Jul 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.3.3-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Tue Jun 23 2020 Fabio Valentini <decathorpe@gmail.com> - 0.3.3-1
- Update to version 0.3.3.

* Tue Apr 14 2020 Josh Stone <jistone@redhat.com> - 0.3.2-1
- Update to 0.3.2

* Fri Mar 20 2020 Fabio Valentini <decathorpe@gmail.com> - 0.3.1-2
- Rebuild for bodhi-rs 0.5.8.

* Sun Mar 08 2020 Fabio Valentini <decathorpe@gmail.com> - 0.3.1-1
- Update to version 0.3.1.

* Sun Mar 08 2020 Fabio Valentini <decathorpe@gmail.com> - 0.3.0-1
- Update to version 0.3.0.

* Thu Mar 05 2020 Fabio Valentini <decathorpe@gmail.com> - 0.2.5-2
- Rebuild for bodhi-rs 0.5.7.

* Mon Feb 24 2020 Fabio Valentini <decathorpe@gmail.com> - 0.2.5-1
- Update to version 0.2.5.

* Wed Feb 19 2020 Fabio Valentini <decathorpe@gmail.com> - 0.2.4-1
- Update to version 0.2.4.

* Mon Feb 10 2020 Fabio Valentini <decathorpe@gmail.com> - 0.2.3-1
- Initial package
