# Generated by rust2rpm 16
# * resolve circular dependency with zbus
%bcond_with check
%global debug_package %{nil}

%global crate zbus_macros

Name:           rust-%{crate}
Version:        1.8.0
Release:        2%{?dist}
Summary:        Proc-macros for zbus

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/zbus_macros
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Proc-macros for zbus.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Wed Jan 27 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.8.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Thu Jan 07 18:34:27 CET 2021 Fabio Valentini <decathorpe@gmail.com> - 1.8.0-1
- Update to version 1.8.0.
- Fixes RHBZ#1913710

* Tue Jan 05 22:21:17 CET 2021 Igor Raits <ignatenkobrain@fedoraproject.org> - 1.7.0-1
- Update to 1.7.0

* Mon Aug 03 01:48:06 +04 2020 Marc-André Lureau <marcandre.lureau@redhat.com> - 1.1.1-1
- Initial package, rhbz#1862949
